"""add weight_change_pct to holding_deltas

Revision ID: 456edea1a8de
Revises: 8444b2b9cb4c
Create Date: 2026-06-17 21:03:32.616836

Note: SQLite does not persist FK/unique-constraint metadata in a way Alembic
can diff against the model, so the autogenerated output was noisy. Only the
genuinely new column is added here.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '456edea1a8de'
down_revision: Union[str, Sequence[str], None] = '8444b2b9cb4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add weight_change_pct column to holding_deltas."""
    op.add_column(
        'holding_deltas',
        sa.Column(
            'weight_change_pct',
            sa.Float(),
            nullable=True,
            comment='权重变化 = weight_curr - weight_prev',
        ),
    )


def downgrade() -> None:
    """Drop weight_change_pct column."""
    op.drop_column('holding_deltas', 'weight_change_pct')
