"""initial schema

Revision ID: 8444b2b9cb4c
Revises:
Create Date: 2026-06-17 20:29:15.870650

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8444b2b9cb4c'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funds',
    sa.Column('fund_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cik', sa.String(length=20), nullable=False, comment='SEC CIK 编号'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='基金公司名称'),
    sa.Column('manager', sa.String(length=255), nullable=True, comment='基金经理'),
    sa.Column(
        'strategy', sa.String(length=100), nullable=True,
        comment='投资策略分类: Growth/Value/Event-Driven/Multi-Strategy 等',
    ),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否仍在追踪'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('fund_id'),
    sa.UniqueConstraint('cik')
    )
    op.create_table('securities',
    sa.Column('cusip', sa.String(length=9), nullable=False, comment='CUSIP 编号'),
    sa.Column('ticker', sa.String(length=20), nullable=True, comment='股票代码'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='公司名称'),
    sa.Column('sector', sa.String(length=100), nullable=True, comment='GICS Sector'),
    sa.Column('industry', sa.String(length=100), nullable=True, comment='GICS Industry'),
    sa.Column('market_cap', sa.BigInteger(), nullable=True, comment='最近市值'),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cusip')
    )
    op.create_table('filings',
    sa.Column('filing_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('accession_number', sa.String(length=50), nullable=False, comment='SEC Accession Number'),
    sa.Column('filing_date', sa.Date(), nullable=False, comment='SEC 收到日期'),
    sa.Column('report_date', sa.Date(), nullable=False, comment='持仓报告日期（季末）'),
    sa.Column('form_type', sa.String(length=20), nullable=False, comment='13F-HR / 13F-HR/A'),
    sa.Column('is_amendment', sa.Boolean(), nullable=True, comment='是否为修正版'),
    sa.Column('total_value', sa.BigInteger(), nullable=True, comment='该期总市值（千美元）'),
    sa.Column('holding_count', sa.Integer(), nullable=True, comment='持仓股票数量'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.fund_id'], ),
    sa.PrimaryKeyConstraint('filing_id'),
    sa.UniqueConstraint('accession_number')
    )
    op.create_index('ix_filings_fund_report', 'filings', ['fund_id', 'report_date'], unique=False)
    op.create_table('fund_overlaps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fund_a_id', sa.Integer(), nullable=False),
    sa.Column('fund_b_id', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.String(length=7), nullable=False, comment='格式: 2024Q3'),
    sa.Column('jaccard_score', sa.Float(), nullable=False, comment='Jaccard 相似度 0~1'),
    sa.Column('overlap_count', sa.Integer(), nullable=False, comment='重叠股票数量'),
    sa.Column('overlap_tickers', sa.Text(), nullable=True, comment='重叠 ticker 列表, 逗号分隔'),
    sa.ForeignKeyConstraint(['fund_a_id'], ['funds.fund_id'], ),
    sa.ForeignKeyConstraint(['fund_b_id'], ['funds.fund_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_a_id', 'fund_b_id', 'quarter', name='uq_overlap')
    )
    op.create_index('ix_overlap_quarter', 'fund_overlaps', ['quarter'], unique=False)
    op.create_table('holding_delta_norms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quarter', sa.String(length=7), nullable=False, comment='格式: 2024Q3'),
    sa.Column('cusip', sa.String(length=9), nullable=False),
    sa.Column('put_call', sa.String(length=10), nullable=True, comment='PUT / CALL / None'),
    sa.Column('consensus_action', sa.String(length=10), nullable=False, comment='NEW / SOLD / ADD / REDUCE'),
    sa.Column('fund_count', sa.Integer(), nullable=False, comment='参与基金数'),
    sa.Column('avg_weight_change_pct', sa.Float(), nullable=False, comment='平均权重变化 %'),
    sa.Column('total_weight_change_pct', sa.Float(), nullable=True, comment='总权重变化 %'),
    sa.Column('signal_score', sa.Float(), nullable=False, comment='信号强度 = fund_count * abs(avg_weight_change_pct)'),
    sa.Column('fund_size_tier', sa.String(length=10), nullable=True, comment='mega / large / medium / small'),
    sa.Column('action_norm_score', sa.Float(), nullable=True, comment='标准化动作强度'),
    sa.Column('conviction_score', sa.Float(), nullable=True, comment='综合置信度'),
    sa.Column('holder_count', sa.Integer(), nullable=True, comment='当前季度持有该标的的基金数'),
    sa.Column('crowding_score', sa.Float(), nullable=True, comment='拥挤度 = holder_count / 总基金数'),
    sa.ForeignKeyConstraint(['cusip'], ['securities.cusip'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quarter', 'cusip', 'put_call', 'consensus_action', name='uq_delta_norm')
    )
    op.create_index('ix_delta_norm_action', 'holding_delta_norms', ['consensus_action'], unique=False)
    op.create_index('ix_delta_norm_quarter', 'holding_delta_norms', ['quarter'], unique=False)
    op.create_table('holding_deltas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('cusip', sa.String(length=9), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('put_call', sa.String(length=10), nullable=True, comment='PUT / CALL / None'),
    sa.Column('quarter', sa.String(length=7), nullable=False, comment='格式: 2024Q3'),
    sa.Column('prev_quarter', sa.String(length=7), nullable=True, comment='上一季度: 2024Q2'),
    sa.Column('action', sa.String(length=10), nullable=False, comment='NEW / SOLD / ADD / REDUCE'),
    sa.Column('shares_prev', sa.BigInteger(), nullable=True),
    sa.Column('shares_curr', sa.BigInteger(), nullable=True),
    sa.Column('shares_change', sa.BigInteger(), nullable=False, comment='变化量'),
    sa.Column('shares_change_pct', sa.Float(), nullable=True, comment='变化百分比'),
    sa.Column('value_prev', sa.BigInteger(), nullable=True),
    sa.Column('value_curr', sa.BigInteger(), nullable=True),
    sa.Column('value_change', sa.BigInteger(), nullable=False),
    sa.Column('weight_prev', sa.Float(), nullable=True),
    sa.Column('weight_curr', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cusip'], ['securities.cusip'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.fund_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'cusip', 'put_call', 'quarter', name='uq_delta')
    )
    op.create_index('ix_deltas_action', 'holding_deltas', ['action'], unique=False)
    op.create_index('ix_deltas_quarter', 'holding_deltas', ['quarter'], unique=False)
    op.create_table('holdings',
    sa.Column('holding_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False, comment='季末日期'),
    sa.Column('cusip', sa.String(length=9), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True, comment='冗余 ticker，加速查询'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='冗余公司名'),
    sa.Column('shares', sa.BigInteger(), nullable=False, comment='持股数量'),
    sa.Column('value', sa.BigInteger(), nullable=False, comment='市值（千美元）'),
    sa.Column('weight_pct', sa.Float(), nullable=True, comment='占该基金总持仓比重 %'),
    sa.Column('put_call', sa.String(length=10), nullable=True, comment='PUT / CALL / None'),
    sa.ForeignKeyConstraint(['cusip'], ['securities.cusip'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.fund_id'], ),
    sa.PrimaryKeyConstraint('holding_id'),
    sa.UniqueConstraint('fund_id', 'report_date', 'cusip', 'put_call', name='uq_holding')
    )
    op.create_index('ix_holdings_report_date', 'holdings', ['report_date'], unique=False)
    op.create_index('ix_holdings_ticker', 'holdings', ['ticker'], unique=False)
    op.create_table('sector_weights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.String(length=7), nullable=False, comment='格式: 2024Q3'),
    sa.Column('sector', sa.String(length=100), nullable=False, comment='GICS Sector 名称'),
    sa.Column('weight_pct', sa.Float(), nullable=False, comment='板块权重占比 %'),
    sa.Column('holding_count', sa.Integer(), nullable=True, comment='该板块持仓数量'),
    sa.Column('total_value', sa.BigInteger(), nullable=True, comment='该板块总市值（千美元）'),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.fund_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'quarter', 'sector', name='uq_sector_weight')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sector_weights')
    op.drop_index('ix_holdings_ticker', table_name='holdings')
    op.drop_index('ix_holdings_report_date', table_name='holdings')
    op.drop_table('holdings')
    op.drop_index('ix_deltas_quarter', table_name='holding_deltas')
    op.drop_index('ix_deltas_action', table_name='holding_deltas')
    op.drop_table('holding_deltas')
    op.drop_index('ix_delta_norm_quarter', table_name='holding_delta_norms')
    op.drop_index('ix_delta_norm_action', table_name='holding_delta_norms')
    op.drop_table('holding_delta_norms')
    op.drop_index('ix_overlap_quarter', table_name='fund_overlaps')
    op.drop_table('fund_overlaps')
    op.drop_index('ix_filings_fund_report', table_name='filings')
    op.drop_table('filings')
    op.drop_table('securities')
    op.drop_table('funds')
    # ### end Alembic commands ###
